### ISSUE TITLE
Unable to use client without plugin

### ISSUE THREAD

**Issue by mshavliuk** [8p/EightPointsGuzzleBundle#258]
| Q                | A
| ---------------- | -----
| Symfony version  | any
| Bundle version   | 7.0-current

Config:
```yaml
eight_points_guzzle:
    clients:
        clients_data:
            class: App\Client\ClientsDataClient
            base_url: 'http://base_url.com/'
            plugin:
                some_plugin: ~

        some_rest:
            class: App\Client\SpmeRestClient
```

After installing the plugin I started to handle this error while cache warming up:
```bash
In EightPointsGuzzleExtension.php line 153:
                                          
Notice: Undefined index: some_plugin  
```

It happens because of the following lines in `src/DependencyInjection/EightPointsGuzzleExtension.php`:
```php
foreach ($this->plugins as $plugin) {
    $plugin->loadForClient($options['plugin'][$plugin->getPluginName()], $container, $clientName, $handler);
}
```

So you can see, that it tries to enable each available plugin for every client, no matter is it specify in client config or not.
