### ISSUE TITLE
Invalid definition for service "eight_points_guzzle.handler_stack.xyz"

### ISSUE THREAD

**Issue by skroberto** [8p/EightPointsGuzzleBundle#286]
| Q                | A
| ---------------- | -----
| Symfony version  | 4.4.0
| Bundle version   | 7.6.0
| PHP version   | 7.1.21
| Guzzle version   | 6.3.3

Hi, not sure if this is a bug in the bundle or a misconfiguration on my side so please help me to track this down.

Symfony 4.4 has introduced a Service Container Linter to check the services defined in the container. This can be run from console: `./bin/console lint:container -vvv`

My linter is failing with this error
```
[Symfony\Component\DependencyInjection\Exception\InvalidParameterTypeException]
Invalid definition for service "eight_points_guzzle.handler_stack.xyz": argument 1 of "GuzzleHttp\HandlerStack::push" accepts "callable", "Symfony\Component\ExpressionLanguage\Expression" passed.
```

My yaml configuration looks like:

```
parameters:
    eight_points_guzzle.symfony_log_formatter.pattern: ">>>>>>>>\n{request}\n<<<<<<<<\n{response}\n--------\n{error}"

eight_points_guzzle:
    clients:
        xyz:
            base_url: "%xyz_api_url%"
            options:
                timeout: 30
                http_errors: true
                headers: []
            plugin: null

```
