### ISSUE TITLE
Autowiring GuzzleHttp\ClientInterface does not work out of the box

### ISSUE THREAD

**Issue by Starojitski** [8p/EightPointsGuzzleBundle#312]
Followed installation instructions:

```
eight_points_guzzle:
    clients:
        default:
            options:
                http_errors: false
```

But when running website get the following exception

![image](https://user-images.githubusercontent.com/4128920/137282685-d3d2f55b-f276-4366-85c7-fd4ce8e21f78.png)

Defining service and alias helped but would rather not have to do this, if possible. Any advice?

```
        <service id="GuzzleHttp\ClientInterface" alias="eight_points_guzzle.client.default"/>
        <service id="eight_points_guzzle.client.default" class="GuzzleHttp\Client" />
```

| Q                | A
| ---------------- | -----
| Symfony version  | 4.4.32
| Bundle version   | 8.2.0
