### ISSUE TITLE
No information in Guzzle Profiler tab

### ISSUE THREAD

**Issue by Starojitski** [8p/EightPointsGuzzleBundle#313]
![image](https://user-images.githubusercontent.com/4128920/137285366-233dcf6c-32b6-447a-a227-0870ffcd2e48.png)

At least 5 guzzle requests were executed but none are shown. 
Configured like this:
```
eight_points_guzzle:
    logging: '%kernel.debug%'
    profiling: '%kernel.debug%'
    clients:
        default:
            lazy: true
            options:
                http_errors: false
``` 

Any advice would be appreciated

| Q                | A
| ---------------- | -----
| Symfony version  | 4.4.32
| Bundle version   | 8.2.0

**Comment by rpkamp** [comment]
1. What is the value of `%kernel.debug%`
2. Are you indeed injecting the `@eight_points_guzzle.client.default` into services that require a Guzzle Client or are you creating (a) Guzzle client(s) elsewhere?

**Comment by florianpreusner** [comment]
Closing issue because of missing additional information. 
Thanks for helping out @rpkamp 🙌

**Comment by nuryagdym** [comment]
I am facing the same issue,

When I make a request using default client `@eight_points_guzzle.client.default_client` it works, I can see guzzle request in symfony profiler.

Problem is with custom clients that I configured. Example:
```yaml
eight_points_guzzle:
  clients:
    logging: true
    default_client:
      options:
        timeout: 10
        headers:
          content-type: 'application/json'

    custom_client:
      logging: true # I tried by adding here also
      base_url: 'https://mydomain'
      options:
        headers:
          content-type: 'application/json'

```
